POST http://budget-app-backend.test/api/incomes HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 3|MIsOIQFH6D00G4K9uOpRjf1vlfbyBbLTynVcmFzr5ff4424e

{
    "name": "New Price 3",
    "amount": 80000
}
